package com.amdox.nexushr;
import jakarta.validation.Valid; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import java.math.*; import java.time.*; import java.util.*;

@RestController @RequestMapping("/api/v1") @CrossOrigin
public class ApiController {
  private final EmployeeRepository employees; private final LeaveRequestRepository leaves; private final AttendanceRecordRepository attendanceRecords;
  ApiController(EmployeeRepository employees, LeaveRequestRepository leaves, AttendanceRecordRepository attendanceRecords){this.employees=employees;this.leaves=leaves;this.attendanceRecords=attendanceRecords;}
  @GetMapping("/employees") List<Employee> employees(@RequestParam(required=false) String department){return department==null?employees.findAll():employees.findByDepartmentIgnoreCase(department);}
  @GetMapping("/employees/{id}") Employee employee(@PathVariable Long id){return employees.findById(id).orElseThrow(()->new NoSuchElementException("Employee not found"));}
  @PostMapping("/employees") ResponseEntity<Employee> create(@Valid @RequestBody EmployeeInput i){var e=new Employee(i.name(),i.email(),i.department(),i.title(),i.status(),LocalDate.now(),i.annualSalary(),i.leaveBalance(),i.engagementScore(),i.attritionRisk()); e.update(i); return ResponseEntity.status(HttpStatus.CREATED).body(employees.save(e));}
  @PutMapping("/employees/{id}") Employee update(@PathVariable Long id,@Valid @RequestBody EmployeeInput i){var e=employee(id);e.update(i);return employees.save(e);}
  @DeleteMapping("/employees/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void delete(@PathVariable Long id){employees.delete(employee(id));}
  @GetMapping("/leaves") List<LeaveRequest> leaves(){return leaves.findAll();}
  @PatchMapping("/leaves/{id}/status") LeaveRequest leaveStatus(@PathVariable Long id,@RequestParam String value){var l=leaves.findById(id).orElseThrow(()->new NoSuchElementException("Leave request not found"));if("MANAGER_APPROVED".equals(value)&&!"MANAGER_APPROVED".equals(l.getStatus())){long days=0; LocalDate start=l.getStartDate(); LocalDate end=l.getEndDate(); while(!start.isAfter(end)){if(start.getDayOfWeek()!=java.time.DayOfWeek.SATURDAY&&start.getDayOfWeek()!=java.time.DayOfWeek.SUNDAY){days++;}start=start.plusDays(1);}l.getEmployee().deductLeave((int)days);employees.save(l.getEmployee());}l.setStatus(value);return leaves.save(l);}
  @GetMapping("/dashboard") Dashboard dashboard(){var all=employees.findAll(); var total=all.size(); var active=all.stream().filter(e->"ACTIVE".equals(e.getStatus())).count(); var avgEngagement=total==0?0:all.stream().mapToInt(Employee::getEngagementScore).average().orElse(0); var cost=all.stream().map(Employee::getAnnualSalary).reduce(BigDecimal.ZERO,BigDecimal::add); var dept=new LinkedHashMap<String,Long>(); all.forEach(e->dept.merge(e.getDepartment(),1L,Long::sum)); return new Dashboard(total,active,leaves.findAll().stream().filter(l->"PENDING".equals(l.getStatus())).count(),Math.round(avgEngagement),cost,dept,all.stream().sorted(Comparator.comparingInt(Employee::getAttritionRisk).reversed()).limit(4).toList());}
  @GetMapping("/attendance/today") Map<String,Object> attendance(){var all=employees.findAll(); long present=all.stream().filter(e->e.isCheckedIn()&&"OFFICE".equals(e.getCheckInType())).count(); long remote=all.stream().filter(e->e.isCheckedIn()&&"REMOTE".equals(e.getCheckInType())).count(); long onLeave=all.stream().filter(e->"ON_LEAVE".equals(e.getStatus())).count(); return Map.of("present",present+remote,"remote",remote,"onLeave",onLeave,"updatedAt",LocalTime.now().withNano(0).toString());}
  @PostMapping("/employees/{id}/clock-in") Employee clockIn(@PathVariable Long id,@RequestParam String type){var e=employee(id); e.clockIn(type); var rec=new AttendanceRecord(e,LocalDate.now(),LocalTime.now().withNano(0),type); attendanceRecords.save(rec); return employees.save(e);}
  @PostMapping("/employees/{id}/clock-out") Employee clockOut(@PathVariable Long id){var e=employee(id); e.clockOut(); var list=attendanceRecords.findByEmployeeIdOrderByDateDescCheckInTimeDesc(id); if(!list.isEmpty()){var latest=list.get(0); if(latest.getCheckOutTime()==null){latest.setCheckOutTime(LocalTime.now().withNano(0)); attendanceRecords.save(latest);}} return employees.save(e);}
  @GetMapping("/employees/{id}/leaves") List<LeaveRequest> employeeLeaves(@PathVariable Long id){var e=employee(id);return leaves.findAll().stream().filter(l->l.getEmployee().getId().equals(id)).sorted(Comparator.comparing(LeaveRequest::getStartDate).reversed()).toList();}
  @PostMapping("/employees/{id}/leaves") ResponseEntity<LeaveRequest> createLeave(@PathVariable Long id,@Valid @RequestBody LeaveRequestInput i){var e=employee(id);var lr=new LeaveRequest(e,i.type(),i.startDate(),i.endDate(),"PENDING",i.reason());return ResponseEntity.status(HttpStatus.CREATED).body(leaves.save(lr));}
  @GetMapping("/employees/{id}/attendance") List<AttendanceRecord> employeeAttendance(@PathVariable Long id){return attendanceRecords.findByEmployeeIdOrderByDateDescCheckInTimeDesc(id);}
  public record Dashboard(long totalEmployees,long activeEmployees,long pendingLeaves,long engagementScore,BigDecimal annualPayroll,Map<String,Long> departmentHeadcount,List<Employee> riskEmployees) {}
}
